version: 1
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
loggers:
  speedtest:
    level: DEBUG
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
